config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  root 'creatives#index'

  resources :locataires
  resources :owners
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/from_matcher.rb
class FromMatcher < ApplicationRecord
   
def compare_forms
    @matches = Owner.find(id)
    if owner.age == locataire.age && owner.sexe == locataire.sexe
        render @matches.all
    end
end

end

app/models/locataire.rb
class Locataire < ApplicationRecord
    validates :name, presence:true
    validates :surname, presence:true
    validates :contact, presence:true
    validates :place, presence:true
    validates :sexe, presence:true
    validates :age, presence:true
    validates :other, presence:true
    validates :loyer, presence:true
    
    after_create :compare_forms
    
        def compare_forms

        owners = Owner.all
            owners.each do |owner|
                if owner.age == age && owner.sexe == sexe
                 FromMatcher.create(locataires_id:id,owner_id: owner.id)
                end
            end
        end

end

app/models/owner.rb
class Owner < ApplicationRecord
    validates :name, presence:true
    validates :surname, presence:true
    validates :contact, presence:true
    validates :place, presence:true
    validates :owner_type, presence:true
    validates :number, presence:true
    validates :age, presence:true
    validates :other, presence:true
    validates :rent, presence:true
    validates :lead, presence:true
    validates :bail, presence:true
    validates :comments, presence:true

    after_create :compare_forms

    def compare_forms
    locataires = Locataire.all
        locataires.each do |locataire|
            if locataire.age == age && locataire.sexe == sexe
             FromMatcher.create(owner_id:id,locataires_id: locataire.id)
            end
        end
    end


    
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 
  def index
    @matchers = FromMatcher.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/controllers/locataires_controller.rb
class LocatairesController < ApplicationController
  before_action :set_locataire, only: [:show, :edit, :update, :destroy]

  # GET /locataires
  # GET /locataires.json
  def index
    @locataires = Locataire.all
  end

  # GET /locataires/1
  # GET /locataires/1.json
  def show
  end

  # GET /locataires/new
  def new
    @locataire = Locataire.new
  end

  # GET /locataires/1/edit
  def edit
  end

  # POST /locataires
  # POST /locataires.json
  def create
    @locataire = Locataire.new(locataire_params)

    respond_to do |format|
      if @locataire.save
        format.html { redirect_to @locataire, notice: 'Locataire was successfully created.' }
        format.json { render :show, status: :created, location: @locataire }
      else
        format.html { render :new }
        format.json { render json: @locataire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locataires/1
  # PATCH/PUT /locataires/1.json
  def update
    respond_to do |format|
      if @locataire.update(locataire_params)
        format.html { redirect_to @locataire, notice: 'Locataire was successfully updated.' }
        format.json { render :show, status: :ok, location: @locataire }
      else
        format.html { render :edit }
        format.json { render json: @locataire.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /locataires/1
  # DELETE /locataires/1.json
  def destroy
    @locataire.destroy
    respond_to do |format|
      format.html { redirect_to locataires_url, notice: 'Locataire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locataire
      @locataire = Locataire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locataire_params
      params.require(:locataire).permit(:name, :surname, :contact, :place, :sexe, :age, :other, :loyer)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
	def index
        @owners = Owner.all
        @owner  = Owner.new
    end

    def create
    	Owner.create(owner_params)
    	redirect_to owners_path
    end

    def owner_params
    	params.require(:owner).permit(:name, :surname, :sexe, :contact, :place, :owner_type, :number, :age, :other, :rent, :lead, :bail, :comments)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
    def match_locataires(match)
        Owner.find(match. locataires_id)
    end
    def match_owner(match)
        Owner.find(match.owner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locataires_helper.rb
module LocatairesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p><%= @matchers. each do |match|%></p>
<p><%= match_owner(match).name%></p>
   <%= match_locataires(match).name%>
<p><%= match_owner(match).age%></p>
<p><%= match_locataires(match).age%></p>
    <%end%>

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">We've got what you need!</h2>
                <hr class="light">
                <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                <a href="#" class="btn btn-default btn-xl">Get Started!</a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Free Download at Start Bootstrap!</h2>
            <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
        </div>
    </div>
</aside>

app/views/creatives/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Des Questions ? Contactez Nous !</h2>
                <hr class="primary">
                <p>Appelez-nous ou envoyez-nous un courriel et nous vous répondrons dans les plus brefs délais!</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>(225) 21-26-98-82 </p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:your-email@your-domain.com">info@oradimmo.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_header.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Bienvenue sur ORAD COLOCATION</h1>
            <hr>
            <p>1ère Plateforme de Colocation en Côte d'Ivoire ! Vous Cherchez un colocataire ou une colocation ? Vous êtes au bon endroit !</p>
            <a href="#about" class="btn btn-primary btn-xl page-scroll">Je cherche une Colocation</a>  <a href="#about" class="btn btn-primary btn-xl page-scroll">Je cherche un colocataire </a>
        </div>
    </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Orad Colocation</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">A Propos de Nous</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Notre Services</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contactez-Nous</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/creatives/_portfolio.html.erb
<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/1.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/2.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/3.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/4.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/5.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/6.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                    <h3>Sturdy Templates</h3>
                    <p class="text-muted">Our templates are updated regularly so they don't break.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Ready to Ship</h3>
                    <p class="text-muted">You can use this theme as is, or you can make changes!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Up to Date</h3>
                    <p class="text-muted">We update dependencies to keep things fresh.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Made with Love</h3>
                    <p class="text-muted">You have to make your websites with love these days!</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/creatives/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'services' %>
<%
=begin %>
<%= render 'call_to_action' %>
<%
=end %>
<%= render 'contact' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colocation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/creative.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orad Colocation</title>
  <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'creative/manifest.js' %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/locataires/_form.html.erb
<%= form_with(model: locataire, local: true) do |form| %>
  <% if locataire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(locataire.errors.count, "error") %> prohibited this locataire from being saved:</h2>

      <ul>
      <% locataire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nom %>
    <%= form.text_field :name, id: :locataire_name %>
  </div>

  <div class="field">
    <%= form.label :Prénom %>
    <%= form.text_field :surname, id: :locataire_surname %>
  </div>

  <div class="field">
    <%= form.label :Contact %>
    <%= form.text_field :contact, id: :locataire_contact %>
  </div>

  <div class="field">
    <%= form.label :Place %>
    <%= form.text_field :place, id: :locataire_place %>
  </div>

  <div class="field">
    <%= form.label :Sexe %>
    <%= form.text_field :sexe, id: :locataire_sexe %>
  </div>

  <div class="field">
    <%= form.label :Age %>
    <%= form.number_field :age, id: :locataire_age %>
  </div>

  <div class="field">
    <%= form.label :Autres %>
    <%= form.text_field :other, id: :locataire_other %>
  </div>

  <div class="field">
    <%= form.label :Loyer %>
    <%= form.number_field :loyer, id: :locataire_loyer %>
  </div>

  <div class="actions">
    
    <%= form.submit "Envoyer" %>
  </div>
<% end %>

app/views/locataires/edit.html.erb
<h1>Editing Locataire</h1>

<%= render 'form', locataire: @locataire %>

<%= link_to 'Show', @locataire %> |
<%= link_to 'Back', locataires_path %>

app/views/locataires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locataires</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Contact</th>
      <th>Lieu d'Habitation</th>
      <th>Sexe</th>
      <th>Age</th>
      <th>Autres</th>
      <th>Loyer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locataires.each do |locataire| %>
      <tr>
        <td><%= locataire.name %></td>
        <td><%= locataire.surname %></td>
        <td><%= locataire.contact %></td>
        <td><%= locataire.place %></td>
        <td><%= locataire.sexe %></td>
        <td><%= locataire.age %></td>
        <td><%= locataire.other %></td>
        <td><%= locataire.loyer %></td>
        <td><%= link_to 'Show', locataire %></td>
        <td><%= link_to 'Edit', edit_locataire_path(locataire) %></td>
        <td><%= link_to 'Destroy', locataire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locataire', new_locataire_path %>

app/views/locataires/new.html.erb
<h1>Formulaire Locataire</h1>

<%= render 'form', locataire: @locataire %>

<%= link_to 'Back', locataires_path %>

app/views/locataires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @locataire.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @locataire.surname %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @locataire.contact %>
</p>

<p>
  <strong>Place:</strong>
  <%= @locataire.place %>
</p>

<p>
  <strong>Sexe:</strong>
  <%= @locataire.sexe %>
</p>

<p>
  <strong>Age:</strong>
  <%= @locataire.age %>
</p>

<p>
  <strong>Other:</strong>
  <%= @locataire.other %>
</p>

<p>
  <strong>Loyer:</strong>
  <%= @locataire.loyer %>
</p>

<%= link_to 'Edit', edit_locataire_path(@locataire) %> |
<%= link_to 'Back', locataires_path %>

app/views/owners/index.html.erb
<h1>Remplissez ce formulaire</h1>
<div>
    <h1>Résultat formulaire</h1>
    <table class="table table-bordered">
        <tr>
            <td>Nom</td>
            <td>prénom</td>
            <td>sexe</td>
            <td>Contact</td>
            <td>Lieu d'habitation</td>
            <td>Type d'habitation</td>
            <td>Nombre de colocataire</td>
            <td>age</td>
            <td>Autres</td>
            <td>Loyer</td>
            <td>Avance</td>
            <td>Caution</td>
            <td>Commentaires</td>

        </tr>
    <% @owners.each do |owner| %>
        <tr>
            <td><%= owner.name%></td>
            <td><%= owner.surname%></td>
            <td><%= owner.sexe %></td>
            <td><%= owner.contact%></td>
            <td><%= owner.place%></td>
            <td><%= owner.owner_type%></td>
            <td><%= owner.number%></td>
            <td><%= owner.age%></td>
            <td><%= owner.other%></td>
            <td><%= owner.rent%></td>
            <td><%= owner.lead%></td>
            <td><%= owner.bail%></td>
            <td><%= owner.comments%></td>
        </tr>

    <% end %>
    </table>
</div>

<div class="container">
    <h1>formulaire</h1>
<%= form_for @owner, method: "post" do |f|  %>
    <%= f.label :Nom %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :prénom %>
    <%= f.text_field :surname, class: "form-control" %>
    <%= f.label :sexe %>
    <%= f.text_field :sexe, class: "form-control" %>
    <%= f.label :contact %>
    <%= f.text_field :contact, class: "form-control" %>
    <%= f.label :Quartier%>
    <%= f.text_field :place, class: "form-control" %>
    <%= f.label :type_de_maison %>
    <%= f.text_field :owner_type, class: "form-control" %>
    <%= f.label :Nombre_de_colocataire %>
    <%= f.text_field :number, class: "form-control" %>
    <%= f.label :age %>
    <%= f.text_field :age, class: "form-control" %>
    <%= f.label :Autres %>
    <%= f.text_field :other, class: "form-control" %>
    <%= f.label :Loyer %>
    <%= f.text_field :rent, class: "form-control" %>
    <%= f.label :Avance %>
    <%= f.text_field :lead, class: "form-control" %>
    <%= f.label :Caution %>
    <%= f.text_field :bail, class: "form-control" %>
    <%= f.label :Commentaires %>
    <%= f.text_field :comments, class: "form-control" %>
    <%= f.submit "Envoyer"%>
    
  <!--  <-- <label>Sexe</label>
    <input type="text" name="sexe">
    <label>Contact</label>
    <input type="number" name="contact">
    <label>Lieu d'habitation</label>
    <input type="text" name="place">
    <label>Type d'habitation</label>
    <input type="text" name="Type">
    <label>Nombre de colocataire</label>
    <input type="number" name="Number">
    <label>Age</label>
    <input type="number" name="age">
    <label>Autres</label>
    <input type="text" name="other">
    <label>Loyer</label>
    <input type="number" name="rent">
    <label>Avance</label>
    <input type="number" name="lead">
    <label>Caution</label>
    <input type="number" name="bail">
    <label>Commentaires</label>
    <input type="text" name="comments">

    <input type="submit" value="envoyer"> -->
<% end %>